name: fuzhana

services:
  db:
    image: mysql:latest
    container_name: fuzhana_db
    hostname: root
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  web:
    container_name: fuzhana_nginx
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/project
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - mysql-network

  php-fpm:
    container_name: fuzhana_php
    depends_on:
      - db
    build:
      context: ./.docker/php-fpm
      dockerfile: ./dockerfile
    volumes:
      - ./:/var/www/project
    networks:
      - mysql-network
volumes:
  db-data:

networks:
  mysql-network: