FROM php:8-fpm

RUN apt update

RUN apt install -y curl \
    git

RUN docker-php-ext-configure pdo_mysql && \
    docker-php-ext-install pdo_mysql


RUN usermod -u 1000 www-data
RUN usermod -a -G www-data root
RUN mkdir -p /var/www
RUN chown -R www-data:www-data /var/www
RUN mkdir -p /var/www/.composer
RUN chown -R www-data:www-data /var/www/.composer

WORKDIR /var/www/project/